# Generated by Django 4.2 on 2023-05-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=30, verbose_name='text1')),
                ('text2', models.CharField(max_length=30, verbose_name='text2')),
                ('text3', models.CharField(max_length=30, verbose_name='text3')),
                ('text4', models.CharField(max_length=30, verbose_name='text4')),
            ],
        ),
    ]
