# Generated by Django 4.2 on 2023-05-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(verbose_name='text info1')),
                ('text2', models.TextField(verbose_name='text info2')),
                ('btn_name', models.CharField(max_length=30, verbose_name='btn name')),
                ('img', models.ImageField(upload_to='images', verbose_name='image')),
            ],
        ),
        migrations.DeleteModel(
            name='HeaderInfo',
        ),
    ]
