# Generated by Django 4.2 on 2023-05-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_indexinfo_delete_headerinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSecondInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('name_text', models.TextField(verbose_name='text name')),
            ],
        ),
    ]
