# Generated by Django 4.2 on 2023-05-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_menuinclude'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=30, verbose_name='prod name')),
                ('prod_price', models.PositiveIntegerField(verbose_name='product price')),
                ('prod_img', models.ImageField(upload_to='images', verbose_name='product image')),
                ('prod_info', models.TextField(verbose_name='product info')),
            ],
        ),
    ]
