# Generated by Django 4.2 on 2023-05-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_menucontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xohararner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xoh_1', models.CharField(max_length=30, verbose_name='anuny')),
                ('xoh_2', models.CharField(max_length=30, verbose_name='ira masin')),
                ('xoh_img', models.ImageField(upload_to='images', verbose_name='nkary')),
            ],
        ),
    ]
