# Generated by Django 4.2 on 2023-05-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_clients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_B',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upp_1', models.CharField(max_length=30, verbose_name='nanana')),
                ('upp_2', models.CharField(max_length=30, verbose_name='dndndnd')),
            ],
        ),
    ]
