# Generated by Django 4.2 on 2023-05-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_client_b'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='user email')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('people_count', models.PositiveIntegerField(verbose_name='people count')),
                ('message', models.TextField(verbose_name='message')),
            ],
        ),
    ]
