# Generated by Django 4.2 on 2023-05-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_book_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='people_count',
            field=models.CharField(max_length=30, verbose_name='people count'),
        ),
    ]
