# Generated by Django 4.2 on 2023-05-04 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_book_table_people_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_img', models.ImageField(upload_to='images', verbose_name='image')),
                ('team_name', models.CharField(max_length=30, verbose_name='team name')),
                ('team_info', models.CharField(max_length=30, verbose_name='information about chief')),
            ],
        ),
    ]
