# Generated by Django 4.2 on 2023-05-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='user name')),
                ('email', models.EmailField(max_length=254, verbose_name='user email')),
                ('subject', models.CharField(max_length=30, verbose_name='subject name')),
                ('message', models.TextField(verbose_name='text')),
            ],
        ),
    ]
