# Generated by Django 4.2 on 2023-05-04 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_table',
            name='date',
            field=models.TextField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='book_table',
            name='people_count',
            field=models.TextField(verbose_name='people count'),
        ),
    ]
