# Generated by Django 4.2 on 2023-05-04 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_book_table_date_alter_book_table_people_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='client_info',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='client_proff',
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_form', to='main.contactform'),
        ),
    ]
