# Generated by Django 4.2 on 2023-05-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_clients_client_info_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
